default: &default
    adapter: mysql2
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: root
    password: root
    # socket: /var/run/mysqld/mysqld.sock

development:
    <<: *default
    database: apiTest

test:
    <<: *default
    database: apiTest_test

production:
    <<: *default
    database: reapp_production
    username: reapp
    password: <%= ENV['ROCKET_ELEVATORS_INFORMATION_SYSTEM_DATABASE_PASSWORD'] %>
