<<<<<<< HEAD
default: &default
    adapter: mysql2
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: root
    password: root
    # socket: /var/run/mysqld/mysqld.sock

development:
    <<: *default
    database: rocketelevatorsfoobar

test:
    <<: *default
    database: reapp_test

production:
    <<: *default
    database: reapp_production
    username: reapp
    password: <%= ENV['ROCKET_ELEVATORS_INFORMATION_SYSTEM_DATABASE_PASSWORD'] %>
=======
default: &default
    adapter: mysql2
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: root
    password: root
    # socket: /var/run/mysqld/mysqld.sock

development:
    <<: *default
    database: rocketelevatorsfoobar

test:
    <<: *default
    database: reapp_test

production:
    <<: *default
    database: reapp_production
    username: reapp
    password: <%= ENV['ROCKET_ELEVATORS_INFORMATION_SYSTEM_DATABASE_PASSWORD'] %>
>>>>>>> 2f31f3b0a6ca43019671cbe45efd914bf5272b55
